name: Build

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
    paths-ignore:
      - LICENSE-Apache
      - LICENSE-MIT
  pull_request:
    paths-ignore:
      - LICENSE-Apache
      - LICENSE-MIT
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install mdbook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz
          mkdir mdbook-path
          mv mdbook mdbook-path
          echo "$(pwd)/mdbook-path" >> $GITHUB_PATH

      - name: Build
        run: mdbook build
